/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************
#include "FreeRTOS.h"
#include "task.h"


#include "app_tasks.h"


// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************

int blanking = 0;
int scan_delay = SLOW_SCAN_DELAY;

// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************

// Comment a function definition and leverage automatic documentation 
/**
  <p><b>Function: Poll_Switches_Task</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
TaskFunction_t PollSwitchesTask ( void * pvParameters )
{
    while (1) {
        // Poll Switches
        // Speed
        if (PORTAbits.RA5 == 1) {
            // Fast
            scan_delay = FAST_SCAN_DELAY;
        } else {
            // Slow
            scan_delay = SLOW_SCAN_DELAY;
        }
        // Blanking
        if (PORTAbits.RA4 == 1) {
            // Blank all the LEDs
            LATGCLR = 1<<6;
            LATDCLR = 1<<4;
            LATBCLR = 1<<11;     
            LATGCLR = 1<<15;

            // Set blanking flag
            blanking = 1;
        } else {
            // Clear blanking flag
            blanking = 0;
        }

        vTaskDelay(SWITCH_POLL_DELAY);     
    }
}

/**
  <p><b>Function: Scan_LEDs_Task</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
TaskFunction_t ScanLEDsTask ( void * pvParameters)
{
    while (1) {
        // Scan LEDs AGD
        if (!blanking) {
            LATGINV = 1<<6;
            vTaskDelay(scan_delay);
        }
        if (!blanking) {      
            LATDINV = 1<<4;
            vTaskDelay(scan_delay);
        }
        if (!blanking) {
            LATBINV = 1<<11;     
            vTaskDelay(scan_delay);
        }
        if (!blanking) {
            LATGINV = 1<<15;
            vTaskDelay(scan_delay);
        }
        vTaskDelay(scan_delay);
    }
}
